# This workflow ensures that our docker images are kept up to date.

name: CD

# Controls when the workflow will run
on:

  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ultra-hologram-297914
        service_account_key: ${{ secrets.GCLOUD}}
        export_default_credentials: true

    - name: checkout
      uses: actions/checkout@v2

    - name: build container image
      run: make image
